// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models
{
    [Index("StudentId", Name = "IX_Courses_StudentId")]
    public partial class Courses
    {
        [Key]
        public int Id { get; set; }
        public int CourseGrade { get; set; }
        [Required]
        public string Topic { get; set; }
        public int StudentId { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("Courses")]
        public virtual Students Student { get; set; }
    }
}